version: '2'
services:
    oori:
      image: biotope/oori
      environment:
        - SERVER_PORT=8080
        - ENDPOINT_URL=http://fuseki:3030/odfData
        - CB_HOSTNAME=biotope.iais.fraunhofer.de
        - CB_PORT=80
      ports:
        - "80:8080"
        - "5005:5005"   # java debugging

    fuseki:
      build: fuseki/
      ports:
        - "3030:3030"

#    o-mi-node:
#      build: o-mi-node/
#      ports:
#       - "8080:8080"
